name: Aeon cache save
description: "Saves the numba and pip cache"

inputs:
  runner_os:
    description: "The runner os"
    required: true

# Action assumes aeon_env_setup has been run
runs:
  using: "composite"
  steps:
    # ============================= Numba Cache =============================
    - name: Check and delete numba cache if it exists
      if: ${{ env.INVALIDATE_NUMBA_CACHE == '1' }} && github.ref == 'refs/heads/main'
      run: |
        if gh cache list --key ${{ env.NUMBA_CACHE_NAME }} | grep -q ${{ env.NUMBA_CACHE_NAME }}; then
          gh cache delete ${{ env.NUMBA_CACHE_NAME }}
        fi
      shell: bash


    - name: Save new numba cache
      uses: actions/cache/save@v4
      if: ${{ env.INVALIDATE_NUMBA_CACHE == '1' }} && github.ref == 'refs/heads/main'
      with:
        path: ${{ env.NUMBA_CACHE_DIR }}
        key: ${{ env.NUMBA_CACHE_NAME }}

    # ============================= Numba Cache =============================

    # ============================== Pip Cache ==============================
    - name: Check and delete numba cache if it exists
      if: ${{ env.INVALIDATE_NUMBA_CACHE == '1' }} && github.ref == 'refs/heads/main'
      run: |
        if gh cache list --key ${{ env.PIP_CACHE_NAME }} | grep -q ${{ env.PIP_CACHE_NAME }}; then
          gh cache delete ${{ env.PIP_CACHE_NAME }}
        fi
      shell: bash

    # If on linux remove pytorch and reinstall with CPU version to reduce size
    - name: Remove GPU version of torch and install CPU version on linux
      run: |
        if python -m pip list | grep -q torch; then
          echo "Torch is installed, uninstalling..."
          python -m pip uninstall torch -y
          echo "Reinstalling torch from specified index URL..."
          python -m pip install torch --index-url https://download.pytorch.org/whl/cpu
        else
          echo "Torch is not installed, installing..."
        fi
      shell: bash


    # Only save the pip cache on main branch
    - name: Save new pip cache
      uses: actions/cache/save@v4
      if: ${{ env.INVALIDATE_NUMBA_CACHE == '1' }} && github.ref == 'refs/heads/main'
      with:
        path: ${{ env.PIP_CACHE_DIR }}
        key: ${{ env.PIP_CACHE_NAME }}

    # ============================== Pip Cache ==============================
