name: Periodic Tests

on:
  schedule:
    # every day at 1:30 AM UTC
    - cron:  "30 1 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check-manifest:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run check-manifest
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: check-manifest --hook-stage manual

  pre-commit:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  run-notebook-examples:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup aeon env variables
        uses: ./.github/actions/aeon_env_setup
        with:
          cache_name: "notebook-examples"
          runner_os: ${{ runner.os }}
          python_version: "3.10"
          invalidate_numba_cache: "true"
          invalidate_pip_cache: "true"

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: python -m pip install .[all_extras,binder,dev]

#      - name: Run example notebooks
#        run: build_tools/run_examples.sh
#        shell: bash
      - name: Run tests
        run: |
          python -m pytest -k 'test_all_estimators' --pyargs aeon.registry
          python -m pytest -k 'test_check_estimator_does_not_raise' --pyargs aeon.utils
          python -m pytest --pyargs aeon.testing.test_softdeps

      - name: Save aeon caches
        uses: ./.github/actions/save_aeon_cache
        with:
          runner_os: ${{ runner.os }}

  test-nosoftdeps:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup aeon env variables
        uses: ./.github/actions/aeon_env_setup
        with:
          cache_name: "nosoftdeps"
          runner_os: ${{ runner.os }}
          python_version: 3.10
          invalidate_numba_cache: "true"
          invalidate_pip_cache: "true"

      - name: Install aeon and dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: python -m pip install .[dev]

      - name: Show dependencies
        run: python -m pip list

      - name: Run tests
        run: |
          python -m pytest -k 'test_all_estimators' --pyargs aeon.registry
          python -m pytest -k 'test_check_estimator_does_not_raise' --pyargs aeon.utils
          python -m pytest --pyargs aeon.testing.test_softdeps

      - name: Save aeon caches
        uses: ./.github/actions/save_aeon_cache
        with:
          runner_os: ${{ runner.os }}

  test-nosoftdeps-full:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup aeon env variables
        uses: ./.github/actions/aeon_env_setup
        with:
          cache_name: "nosoftdeps-full"
          runner_os: ${{ runner.os }}
          python_version: "3.10"
          invalidate_numba_cache: "true"
          invalidate_pip_cache: "true"

      - name: Install aeon and dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: python -m pip install .[dev]

      - name: Show dependencies
        run: python -m pip list

      - name: Run tests
        run: python -m pytest -k 'not TestAll'

      - name: Save aeon caches
        uses: ./.github/actions/save_aeon_cache
        with:
          runner_os: ${{ runner.os }}

#  pytest:
#    runs-on: ${{ matrix.os }}
#
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ ubuntu-20.04, macOS-13, windows-2022 ]
#        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
#
#    steps:
#      - name: Checkout main
#        uses: actions/checkout@v4
#
#      - name: Setup Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: ${{ matrix.python-version }}
#
#      - name: Setup aeon env variables
#        uses: ./.github/actions/aeon_env_setup
#        with:
#          cache_name: "pytest"
#          runner_os: ${{ runner.os }}
#          python_version: ${{ matrix.python-version }}
#          invalidate_numba_cache: "true"
#          invalidate_pip_cache: "true"
#
#      - name: Install aeon and dependencies
#        uses: nick-fields/retry@v3
#        with:
#          timeout_minutes: 30
#          max_attempts: 3
#          command: python -m pip install .[all_extras,dev]
#
#      - name: Show dependencies
#        run: python -m pip list
#
##      - name: Run tests
##        run: python -m pytest
#      - name: Run tests
#        run: |
#          python -m pytest -k 'test_all_estimators' --pyargs aeon.registry
#          python -m pytest -k 'test_check_estimator_does_not_raise' --pyargs aeon.utils
#          python -m pytest --pyargs aeon.testing.test_softdeps
#
#      - name: Save aeon caches
#        uses: ./.github/actions/save_aeon_cache
#        # We only need caches for python 3.8, 3.10, and 3.12
#        if: ${{ matrix.python-version }} == "3.8" || ${{ matrix.python-version }} == "3.10" || ${{ matrix.python-version }} == "3.12"
#        with:
#          runner_os: ${{ runner.os }}

  codecov:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Disable Numba JIT
        run: echo "NUMBA_DISABLE_JIT=1" >> $GITHUB_ENV

      - name: Install aeon and dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: python -m pip install .[all_extras,unstable_extras,dev]

      - name: Show dependencies
        run: python -m pip list

      - name: Run tests
        run: python -m pytest --cov=aeon --cov-report=xml --timeout 1800

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
